### ISSUE TITLE
2.4-0 release

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#174]
I would like to release **vegan** 2.4-0 before northern mid-summer. I have updated issue #155 to the current state of major changes (those that are not yet released in 2.3-5). The changes are extensive and numerous, and some testing is needed. For the currently merged changes, the following things should be done:

- [x] We have now new `adonis2`. I think the new code should be renamed plain `adonis`, and the old `adonis` should be called something else. I don't know yet how to call this, but calling it `tammuz` would probably stretch the joke too much. The dot naming as `.adonis` (like @EDiLD suggested) would make the function invisible and cannot be used. @gavinsimpson was also concerned about backward compatibility of new `adonis` (issue #156), but we have not made any policy decision for this issue. **Update 8/6/16:** Old `adonis` kept his name, and the resurrected one is still called `adonis2`.

- [x] `dbrda` support functions should be checked (and this is really boring), and the original `dbRDA.D` by @legendre should be removed as un-needed (all of it is now in `dbrda` and `dbRDA.D` serves as a testing platform and proof of the concept).

In addition we have some unsettled things: 

- [x] We have an unmerged pull request #121 by @guiblanchet which conflicts with the `master` and cannot be merged. It also fails `R CMD check` in github. The PR is also pretty large and diffuse. There are formatting problems and github claims that the PR changes 611 files and therefore it is impossible to review the actual changes. I do think that a more minimal and gradual approach would be better: start a new fork and add needed functions one by one always checking that they work, and only add the minimal set of necessary functions -- some of them now duplicate old **vegan**. I don't have time to do this myself before mid-summer, but a cleaner solution is needed for the release. **Update after CRAN release:** We have a credible plan of adding consensus ordination later. It is a safe addition as it does not influence other **vegan** functionality and can also be done in minor releases.

- [x] @gavinsimpson has an unmerged fork on `plot.betadisper`. I think all that is needed is policy decision and merge. There is an extensive discussion in issue #166 

- [x] @psolymos has an unmerged fork on binding `simmat` objects (discussed in issue #164). The changes are pretty large, but I don't know how close they are the target @psolymos set to himself. **Update on 24/5/16:** basically solved with PR #175, although minor cleanup remains (issue #177).

- [x] issue #159 discusses re-designing obsolete `permatswap` and `permatfull` but we have no implementation nor a roadmap. Now these functions are somewhat obsolescent and may not work completely with the upgraded `commsim` & `nullmodel`.   **Update 14/6/16:** As discussed with @psolymos , this is a longer-term issue, and we do not need that in 2.4-0 release, but we do it sometimes during 2.5-0 development (with an option of merging to cran-2.4 branch).

**Comment by psolymos** [comment]
@jarioksa : the unmerged fork for `smbind` related to issue #164 works as expected. Examples cover the use cases and results are as expected. I will check once more and create a PR.

Note that the branch `bind-simmat` also fixes some issues with start/end/thin values in `as.ts.oecosimu`, `simulate.nullmodel`, and `update.nullmodel`.

**Comment by gavinsimpson** [comment]
@jarioksa I'll handle the `plot.betadisper()` changes shortly (I got sidetracked with coenocliner and life).

**Comment by jarioksa** [comment]
I would like to release **vegan** 2.4-0 by June 15, 2016. If I can't do it by then it, the release may well be delayed by two months. 

I'm done with `adonis2` and `dbrda` fixes. @gavinsimpson seems to have an easy merge to be done (must be decided **what** to merge, though). I think that @psolymos also can merge his fixes pretty easily. There will be work to be done, but they are not release critical, but can quite well go to minor releases later (first minor release would probably be in August or early September if we release now). @guiblanchet seemingly closed his PR. The functions can be merged, but they should be merged less intrusively. They are also that separate that they can be merged in minor release, and I would not regard them as release critical -- unless you disagree.

So what do you think? Release now with things we have, and have minor releases to fill in the gaps. Or alternatively, delay release till mid-August and work peacefully for a more finished release.

**Comment by psolymos** [comment]
@jarioksa: let's move ahead with the June 15, 2016 and leave outstanding issues for later. On the null model front: I created and merged PR #180 which also led to closing #177.

**Comment by guiblanchet** [comment]
Hi ! 

I tried to add the function related to consensus RDA to the github repository and I got a message saying that I did not have the permission to make the commit.

Maybe someone could help me with this, I am somewhat new to github, so hopefully this is an easy fix.

Guillaume

**Comment by jarioksa** [comment]
@guiblanchet : check the github help, specifically https://help.github.com/articles/fork-a-repo/ . Essentially you should create a personal fork of **vegan** in your own user area, and then suggest a pull request. You should brows some other help pages as well. I think previously the major problems were caused by Windows file handling, and you should check https://help.github.com/articles/dealing-with-line-endings/#platform-windows to handle those.

**Comment by gavinsimpson** [comment]
I've merged my changes to `plot.betadisper`; the function now only draws data ellipses and has the same conventions as `ordiellipse` in terms of `conf`, which I must say I find confusing but it would be worse if we had two things working differently.

**Comment by jarioksa** [comment]
**vegan** 2.4-0 was released on June 15, 2016. Not all points raised in this issue were included in this release, but we have a credible plan of having them in minor releases (next is to be expected in September).
