### ISSUE TITLE
Checklist for vegan 2.5-0 release

### ISSUE THREAD

**Issue by jarioksa** [vegandevs/vegan#235]
I wish to publish vegan 2.5-0 "asap". This "asap" may be as late as September 2017, but with some luck it can be be earlier. There are big changes, and these are mega-issues that must be finished for the release:

- [ ] Finish new infrastructure for constrained ordination with several issues to be solved (detecting rank, handling zero-rank components).
- [ ] Finish moving to compiled code in `anova.cca`, potentially with new tests.
- [ ] Registration and use of compiled code.

(This entry is the first version of this this issue and rather regarded as a place-holder for future checklist)

**Comment by gavinsimpson** [comment]
I know I haven't looked at the new MLM-based diagnostics yet (but now that summer is here, well spring on the prairies but classes ended anyway, I will look at those), but are you proposing that we merge these or is their absence from the list above indicative?

**Comment by jarioksa** [comment]
The MLM statistics were already merged to the master and `as.mlm()` functions are now deprecated (see issue #235). My main purpose was to list outstanding issues to remind what still must be done.
